CREATE TABLE IF NOT EXISTS ltv_driver (
        driver_uuid VARCHAR(64) PRIMARY KEY,
        ltv FLOAT,
        city_id INT,
        city_name VARCHAR(32),
        lat FLOAT,
        lng FLOAT,
        region VARCHAR(32),
        mega_region VARCHAR(16),
        channel VARCHAR(32),
        driver_flow VARCHAR(16),
        is_uber_email BOOLEAN,
        is_subscribed_email BOOLEAN,
        is_subscribed_sms BOOLEAN,
        engagement VARCHAR(16),
        experience VARCHAR(32),
        extraversion_level VARCHAR(32),
        conscientiousness_level VARCHAR(32),
        agreeableness_level VARCHAR(32),
        lifecycle VARCHAR(16),
        tenure VARCHAR(64),
        churn VARCHAR(32),
        is_comparison_shopper BOOLEAN,

        INDEX (city_id),
        INDEX (region),
        INDEX (mega_region),
        INDEX (channel)
    )
